"""Backend configuration constants."""

from pathlib import Path

BASE_DIR = Path(__file__).parent.parent
MODELS_DIR = BASE_DIR / "models"
MODEL_PATH = MODELS_DIR / "eye_cnn_best.h5"
THRESHOLD_PATH = MODELS_DIR / "eye_threshold.json"

# Resize before MediaPipe to keep CPU usage reasonable.
RESIZE_WIDTH = 640
RESIZE_HEIGHT = 360

# Temporal smoothing for CNN open-eye probability.
EMA_ALPHA = 0.4

# Blink detection state machine.
BLINK_MIN_CLOSED_FRAMES = 1
BLINK_MAX_DURATION_SECONDS = 0.8
BLINK_COOLDOWN_FRAMES = 3
EAR_CLOSED_FALLBACK = 0.16
EAR_BORDERLINE_FALLBACK = 0.20
EAR_CALIBRATION_WINDOW = 90
EAR_BASELINE_MIN_SAMPLES = 12
EAR_BASELINE_PERCENTILE = 85.0
EAR_BASELINE_MIN = 0.20
EAR_BASELINE_MAX = 0.40
EAR_CLOSED_RATIO = 0.68
EAR_BORDERLINE_RATIO = 0.83
EAR_CLOSED_MIN = 0.14
EAR_CLOSED_MAX = 0.26
EAR_BORDERLINE_MIN = 0.17
EAR_BORDERLINE_MAX = 0.32
EAR_MIN_GAP = 0.016
EYE_CNN_WEIGHT = 0.45
EYE_EAR_WEIGHT = 0.55
EYE_CLOSED_DECISION_MIN = 0.62
EYE_OPEN_GUARD_PROB = 0.54
EYE_STRONG_CLOSED_EAR_MARGIN = 0.015

# Yawn detection state machine.
MAR_THRESHOLD = 0.55
MAR_HIGH_THRESHOLD = 0.68
MAR_CONSEC_MIN = 2

# Sliding fatigue window. At 5 FPS, 300 frames is about 60 seconds.
WINDOW_SIZE = 300
FATIGUE_WINDOW_SECONDS = 60.0
RECENT_YAWN_WINDOW_SECONDS = 30.0

# Fatigue score normalization.
PERCLOS_ALERT = 0.08
PERCLOS_CEIL = 0.40
NORMAL_BLINK_RATE = 15.0
MAX_BLINK_DEV = 10.0
EYE_CLOSURE_RATE_MAX = 30.0
YAWN_RATE_MAX = 4.0
RECENT_YAWN_RATE_MAX = 2.0

# Score smoothing and status hysteresis.
SCORE_EMA_ALPHA = 0.28
ALERT_THRESHOLD = 45.0
CRITICAL_THRESHOLD = 78.0
ALERT_RECOVERY_THRESHOLD = 36.0
CRITICAL_RECOVERY_THRESHOLD = 66.0
ALERT_MIN_HOLD_FRAMES = 3
CRITICAL_MIN_HOLD_FRAMES = 8
MILD_PERCLOS_CAP = 0.18
MILD_EYE_CLOSURE_RATE_CAP = 8.0
MILD_STATE_SCORE_CAP = 67.0
SUSTAINED_EYE_CLOSED_START_SECONDS = 3.0
SUSTAINED_EYE_CLOSED_TAU_SECONDS = 1.8
SUSTAINED_EYE_CLOSED_GAIN = 6.0
SUSTAINED_EYE_CLOSED_MAX_BONUS = 35.0

# Reduce CNN contribution for uncertain probabilities near 0.5.
UNCERTAINTY_MARGIN = 0.05

# WebSocket frame processing cap.
PROCESS_INTERVAL = 0.15
MAX_PROCESSING_FPS = 8

# Diagnostics.
FPS_LOG_INTERVAL = 10.0
